### ISSUE TITLE
Semantic version wrong

### ISSUE THREAD

**Issue by DusteDdk** [bendrucker/postgres-date#11] opened 2020-04-14 09:41 UTC
This rounding fix is correct, but it is incompatible with previous behaviour, meaning that software depending on the exact behaviour of this library breaks.

The major number must be increased as this changes previous behaviour.
A new minor version without the fix should be published.

**Comment by bendrucker** [comment] 2020-04-14 15:55
Not the right tone to be taking, please reconsider how you make your case here. 

If the previous behavior was a bug, fixing it is a patch. Everything can be a breaking change to someone, so only breaking API changes are strictly major bumps. Everything else is subjective. 

@salper Can you weigh in on whether the previous behavior was a bug? The intent of this library (and other related pg type modules) is to represent PG data as accurately as possible in JS. That’s why I interpreted #10 as a bug fix.

**Comment by DusteDdk** [comment] 2020-04-14 22:46
I mean no offence, English is not my native language.
This is not a backwards compatible bugfix, as existing software using the library can have implicit reliance on the old behaviour. The patch version meant only for bugfixes, and the major version is also not meant only for api-call-level interface changes. https://semver.org/ section 6.

The idea behind semver is, as seen from the user/package manager of a library/module:
As long as you're stay on this Major, everything you're already using will work as always.
If you bump the minor version, you'll get MORE features than you got now, but no changed behaviour of the existing functionality you're using.
If you bump the patch, you might get more stability and/or performance.

Most important for this case: If you bump major version, you can expect new/changed behaviour and/or API interfaces and you can expect your software not to work correctly without adapting to those changes. This means that any change to a software that causes it to behave differently than before, has to increase the major version. A thumb of rule: If you had to change a unit test expectation, you've broken the existing API behaviour and must bump major.

The question of whether something is a bug or not is not relevant to semver, but I'll entertain that train of thought too, though I'm no authority on that.
Yes, that the module did not round is a wrong behaviour, but a consistent one, it is not depending on some odd state or edge-case, it always behaves the same, so, from a behavioural point of view, it's not a bug, it's just how it behaves. A bug would be something like "on mondays, it does not round ms" or "if you convert three times in a row, do a spin around yourself and then the fourth will not be rounded correctly", something with state and/or edge-cases.

No, everything can not be breaking to someone if their code is correct.
Let us say that you improve the performance, and someone has a race-condition lurking, that's on them, they wrote it wrong.

**Comment by bendrucker** [comment] 2020-04-14 23:28
Other than this, I just don't agree with your interpretation , and don't think you're appreciating the ambiguity here:

> If you had to change a unit test expectation, you've broken the existing API behaviour and must bump major.

If behavior is described in the API documentation, a change is uncontrovertibly breaking. A unit test isn't as clear a contract and doesn't transmit intent. 

<a href="https://xkcd.com/1172/">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/808808/79282703-b108d280-7e6a-11ea-8349-01260c34493a.png">
</a>

This was just the first article that turned up in Google:

https://dev.to/turnerj/should-behavioural-changes-be-considered-breaking-changes-under-semver-2d5n

If you slim down the argument to "versions are free, when in doubt just choose a major bump" I can get behind that.

**Comment by DusteDdk** [comment] 2020-04-14 23:38
Alright then, thanks for hearing me out :)

**Comment by bendrucker** [comment] 2020-04-14 23:38
That said:

> If behavior is described in the API documentation, a change is uncontrovertibly breaking.

Because there's minimal API documentation here for behavior, I'll err on the side of a new major, while adding appropriate documentation. 

The intent of this library remains to correctly parse date strings from Postgres. 

In the future, valid values that can be returned by Postgres that are parsed incorrectly, resulting in loss of data/precision, _will_ be released as bug fixes.

As always, if you do not want your dependencies to change unexpectedly, lock them down and upgrade when you want.

**Comment by salper** [comment] 2020-04-15 08:57
> Can you weigh in on whether the previous behavior was a bug?
Clearly, it's a bug. As the sorting for example was inconsistent. IMHO, developers adapted and fixed this in their code, so some will obviously have breaking changes. But it's not a an interface update. So I think it should stay as a patch.

**Comment by DusteDdk** [comment] 2020-04-15 10:03
Okay, I do not think it is in the spirit of semver that one bumps patch with breaking changes no matter why that is (short of downstream users using the api wrong), and an interface is not only on the input surface but also the output result. But it's your project and it's not really worth a lot of trouble arguing over such a minor thing, it just caught my eye after a rather interesting debug procedure, and I wanted to notify you that someone else may be affected as well, nobody else have complained so I am sure it's no big issue.

Again, thank you for hearing me out, I've adapted the failing tests to expect the new results and am on with life :)

Best Regards, and keep up the good work!

**Comment by bendrucker** [comment] 2020-04-15 16:00
> it just caught my eye after a rather interesting debug procedure

This is ultimately what I'd like to hear about (exactly what this broke for you), as opposed to your interpretation of the semver spec.

I included the XKCD comic as a lighthearted example of how "breaking" is relative to the user. It's a contrived example of clearly unintended behavior.

When we get back to less contrived examples, it's a bit less clear. This is also of interest:

>  I've adapted the failing tests to expect the new results

This opens up even harder questions. As `@salper` noted, "the sorting for example was inconsistent." What if you were returning incorrect data to your end user, and this change results in sending correct data? What if you never had a unit test against the behavior, and adopting a new version transparently fixed your application?

An expansive definition of breaking changes is easier to reason about and I can understand taking a strict interpretation. I'm trying to factor in intent and how this is likely to affect the correctness of user's code, which certainly adds significant ambiguity, and risks at least breaking tests.

Based on this discussion I'm going to go ahead and keep the patch version in place while adding some documentation on the behavioral contract this package is trying to maintain. Thanks!

**Comment by bendrucker** [comment] 2020-04-15 17:27
ce0b2da

**Closed by bendrucker** 2020-04-15 17:27 UTC
